version: "3.8"
services:
  app:
    build: .
    container_name: mini-cloud-app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./app/uploads:/app/uploads
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: mini-cloud-nginx
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/static:/app/static:ro
      - ./app/uploads:/app/uploads:ro
    restart: unless-stopped
